// <auto-generated />
namespace SalamatKoodak.Models
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initial7778889 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial7778889));
        
        string IMigrationMetadata.Id
        {
            get { return "202009060635533_initial7778889"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
