// <auto-generated />
namespace SalamatKoodak.Models
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initial556777 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial556777));
        
        string IMigrationMetadata.Id
        {
            get { return "202008311911277_initial556777"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
